// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace SustavZaPreporukuVideoIgaraML.Model
{
    public class ModelInput
    {
        [ColumnName("game_name_id"), LoadColumn(0)]
        public string Game_name_id { get; set; }


        [ColumnName("platform"), LoadColumn(1)]
        public string Platform { get; set; }


        [ColumnName("esrb"), LoadColumn(2)]
        public string Esrb { get; set; }


        [ColumnName("singleplayer"), LoadColumn(3)]
        public float Singleplayer { get; set; }


        [ColumnName("multyplayer"), LoadColumn(4)]
        public float Multyplayer { get; set; }


        [ColumnName("coop"), LoadColumn(5)]
        public float Coop { get; set; }


        [ColumnName("price"), LoadColumn(6)]
        public float Price { get; set; }


        [ColumnName("ign_rating"), LoadColumn(7)]
        public float Ign_rating { get; set; }


        [ColumnName("campaign_duration"), LoadColumn(8)]
        public float Campaign_duration { get; set; }


        [ColumnName("is_popular"), LoadColumn(9)]
        public float Is_popular { get; set; }


        [ColumnName("char_customization"), LoadColumn(10)]
        public float Char_customization { get; set; }


        [ColumnName("world_size"), LoadColumn(11)]
        public float World_size { get; set; }


        [ColumnName("world_diversity"), LoadColumn(12)]
        public float World_diversity { get; set; }


        [ColumnName("graphics"), LoadColumn(13)]
        public float Graphics { get; set; }


        [ColumnName("period"), LoadColumn(14)]
        public string Period { get; set; }


        [ColumnName("modding"), LoadColumn(15)]
        public float Modding { get; set; }


        [ColumnName("competitive"), LoadColumn(16)]
        public float Competitive { get; set; }


        [ColumnName("genre"), LoadColumn(17)]
        public string Genre { get; set; }


        [ColumnName("type"), LoadColumn(18)]
        public string Type { get; set; }


        [ColumnName("optimization"), LoadColumn(19)]
        public float Optimization { get; set; }


    }
}
